server:
  port: 8080
spring:
  application:
    name: back
  profiles:
    active: "local" # 개발 환경은 로컬로 설정
---
# 개발 환경
spring:
  application:
    name: local
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:postgresql://localhost:5432/trippop
    username: user
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        show-sql: true
        hbm2ddl:
          auto: update
---
# 운영 환경
spring:
  config:
    activate:
      on-profile: "prod"